FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG MONGO_URI
ARG JWT_SECRET
ARG API_KEY
ARG NODE_ENV=production
ARG PORT=5000

ENV MONGO_URI=$MONGO_URI
ENV JWT_SECRET=$JWT_SECRET
ENV API_KEY=$API_KEY
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT

EXPOSE 5000
CMD ["node", "src/server.js"]